export const statuses:any = {
	ONHOLD: {frontend: 'On Hold', backend: 'onHold'},
	BACKLOG: {frontend: 'Backlog', backend: 'backlog'},
	SPRINT: {frontend: 'In Sprint', backend: 'inSprint'},
	INDEV: {frontend: 'In Development', backend: 'inDev'},
	PCRNEED: {frontend: 'PCR - Needed', backend: 'pcrNeeded'},
	PCRPASS: {frontend: 'PCR - Passed', backend: 'pcrPass'},
	PCRCOMP: {frontend: 'PCR - Completed', backend: 'pcrCompleted'},
	CRWORK: {frontend: 'Code Review - Working', backend: 'crWorking'},
	CRFAIL: {frontend: 'Code Review - Failed', backend: 'crFail'},
	QAREADY: {frontend: 'QA Ready', backend: 'qaReady'},
	INQA: {frontend: 'In QA', backend: 'inQa'},
	QAFAIL: {frontend: 'QA Fail', backend: 'qaFail'},
	QAPASS: {frontend: 'QA Pass', backend: 'qaPass'},
	MERGECODE: {frontend: 'Merge Code', backend: 'mergeCode'},
	MERGECONF: {frontend: 'Merge Conflict', backend: 'mergeConflict'},
	UCTREADY: {frontend: 'Ready For UCT', backend: 'uctReady'},
	INUCT: {frontend: 'In UCT', backend: 'inUct'},
	UCTFAIL: {frontend: 'UCT Fail', backend: 'uctFail'},
	UCTPASS: {frontend: 'UCT Pass', backend: 'uctPass'},
	RELEASE: {frontend: 'Ready For Release', backend: 'releaseReady'},
	REMOVEPCR: {frontend: 'Remove PCR Needed', backend: 'removePcrNeeded'},
	REMOVEPCRC: {frontend: 'Remove PCR Completed', backend: 'removePcrCompleted'}
}